version: '3.8'

services:
  web:
    image: yashs3324/portfolio:latest
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3004:3004"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/demo_website?schema=public
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=demo_website
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge 